project_name: 'classification_dogs'
chkpt_dir: '/content/drive/MyDrive/classification_dogs/checkpoints'
num_epochs: 20
data_dir: '/content/drive/MyDrive/classification_dogs/data/imagewoof2-160'
img_size:
  - 160
  - 160
batch_size: 32
model_name: 'resnet18'
num_classes: 10
lr: 0.001
momentum: 0.9
step_size: 10
gamma: 0.1



