project_name: 'classification_dogs'
chkpt_dir: 'checkpoints'
num_epochs: 20
data_dir: 'data/imagewoof2-160'
splits:
  - 'train'
  - 'val'
batch_size: 8
model_name: 'resnet18'
num_classes: 10
lr: 0.001
momentum: 0.9
step_size: 10
gamma: 0.1



